name: Continuous Testing with CITS
on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

env:
   ENVIRONMENT_TO_EXECUTE: TEST
   REMOTE_GRID_URL: ${{ secrets.REMOTE_EXECUTION_URL }}

jobs:
  build:
   
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
     - name: Setup Java 11
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '11'
     - name: Setup Permissions
       run: chmod -R 755 ./
     - name: Run CITS Test
       run: ./Run.command -run -project_location "Projects/MyFirstProject" -release "Release1" -testset "Set1" -setEnv "run.ExecutionMode=Grid" -setEnv "run.RemoteGridURL=$REMOTE_GRID_URL" -setEnv "run.TestEnv=$ENVIRONMENT_TO_EXECUTE"
     - name: Upload Results
       uses: actions/upload-artifact@v3
       with:
        name: Test Results
        path: Projects/MyFirstProject/Results/TestExecution/Release1/Set1/Latest