name: Continuous Testing with CITS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  ENVIRONMENT_TO_TEST: TEST    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Set Permissions
      run: chmod -R 755 ./

    - name: Execute Testset
      run: ./Run.command -run -project_location "Projects/MyFirstProject" -release "Release1" -testset "Set1" -setEnv "run.RemoteGridURL=$ {{ secret.REMOTE_EXECUTION_URL }}" -setEnv "run.ExecutionMode=Grid" -setEnv "run.TestEnv=$ENVIRONMENT_TO_TEST"

    - name: Upload Test Results
      uses: actions/upload-artifact@v3.1.1
      with:
        name: TestResults
        path: Projects/MyFirstProject/Results/TestExecution/Release1/Set1/Latest/
